;Aquest joc de proves serveix per comprovar que l'assignació de variables locals let siguin correctament interpretats
;També comprova que les expressions s'avaluin de forma correcta amb els read

;Variables globals
(define a 1)
(define b 2)
(define c 3)

;Main

(define (main)
    ;Test bàsic amb una variable local nova
    (display "Test 1: let amb una variable local")
    (newline)
    (display "Expressió a avaluar: d + 1")
    (newline)
    (display "Introdueix un valor per d: ")
    (let ((d (read)))
        (display "Avaluació: ")
        (display d) 
        (display " + 1 = ")
        (display (+ d 1)))
    (newline)
    (newline)
    
    ;Test amb múltiples variables locals noves
    (display "Test 2: let amb múltiples variables locals")
    (newline)
    (display "Expressió a avaluar: (d + e) * f")
    (newline)
    (display "Introdueix un valor per d: ")
    (let ((d (read)))
        (display "Introdueix un valor per e: ")
        (let ((e (read)))
            (display "Introdueix un valor per f: ")
            (let ((f (read)))
                (display "Avaluació: (")
                (display d)
                (display " + ")
                (display e)
                (display ") * ")
                (display f)
                (display " = ")
                (display (* (+ d e) f)))))
    (newline)
    (newline)
    
    ;Test amb diferents tipus de dades
    (display "Test 3: let amb diferents tipus")
    (newline)
    (display "Es mostraran els valors introduits")
    (newline)
    (display "Introdueix un número: ")
    (let ((num (read)))
        (display "Introdueix un string: ")
        (let ((text (read)))
            (display "Introdueix un booleà (1/0): ")
            (let ((valor (read)))
                (display "Avaluació: ")
                (display num) (display " ")
                (display text) (display " ")
                (display (= valor 1)))))
    (newline)
    (newline)
    
    ;Test amb let anidats amb noves variables
    (display "Test 4: let anidats")
    (newline)
    (display "Expressió a avaluar: d + e + f")
    (newline)
    (display "Introdueix primer número (d): ")
    (let ((d (read)))
        (display "Introdueix segon número (e): ")
        (let ((e (read)))
            (display "Introdueix tercer número (f): ")
            (let ((f (read)))
                (display "Avaluació: ")
                (display d)
                (display " + ")
                (display e)
                (display " + ")
                (display f)
                (display " = ")
                (display (+ d e f)))))
    (newline)
    (newline)
    
    ;Test accedint a variables globals des de let
    (display "Test 5: let accedint a globals (a=1, b=2, c=3)")
    (newline)
    (display "Expressions a avaluar: a + (b * d), c * e")
    (newline)
    (display "Introdueix multiplicador per b (d): ")
    (let ((d (read)))
        (display "Introdueix multiplicador per c (e): ")
        (let ((e (read)))
            (display "Avaluació 1: a + (b * ")
            (display d)
            (display ") = ")
            (display (+ a (* b d)))
            (newline)
            (display "Avaluació 2: c * ")
            (display e)
            (display " = ")
            (display (* c e))))
    (newline))
